feat(#121): mem_base
h1alexbel/fakehub pull request #123
Opened 2024-08-27 14:48 UTC by h1alexbel

In this pull I've implemented `MemBase` with [rusqlite](https://github.com/rusqlite/rusqlite) to transfer Storage logic from `xml/storage.rs` to `db/mem_base.rs` in the future PRs.

History:
- **feat(#73): xpath**
- **feat(#73): no print**
- **feat(#121): pg_base**
- **feat(#121): ghiqc 0.0.5**
- **feat(#121): pg off, mem_base**
- **feat(#121): initial_schema**
- **feat(#121): checks_jeff_github**
- **feat(#121): puzzle**
- **feat(#121): puzzle for migrations**
- **feat(#121): puzzle, clean for cargo**

related to #121

2024-08-27 22:46 UTC, l3r8yJ commented on server/src/objects/user.rs
> +        // };
commented code

2024-08-27 22:48 UTC, l3r8yJ requested changes
@h1alexbel I have a general question. Why we need `sql` database? I think if we're choosing in memory solution we can use just some list(or any other collection) of data structs. IMHO it would be much simpler then have some `sql` storage. No requests needed. Need to add/remove something –  just call `github#add_user`/`github#add_repo` and etc. If we need some history of changes we can build some state machine that will track all changes that was made by user and it would build report based on it's history

2024-08-27 22:48 UTC, l3r8yJ commented on server/src/objects/user.rs
> +        // };
commented code in repo

2024-08-27 22:48 UTC, l3r8yJ commented on server/src/objects/user.rs
> +        let jeff = User::new(String::from(expected), Storage::new(None));
user have a storage, wrong hierarchy I suppose

2024-08-28 11:44 UTC, h1alexbel commented
> @h1alexbel I have a general question. Why we need `sql` database? I think if we're choosing in memory solution we can use just some list(or any other collection) of data structs. IMHO it would be much simpler then have some `sql` storage. No requests needed. Need to add/remove something – just call `github#add_user`/`github#add_repo` and etc. If we need some history of changes we can build some state machine that will track all changes that was made by user and it would build report based on it's history

@l3r8yJ I thought about that. We can create some data structures in memory and operate with them. In the end we should obtain a hierarchy of these structures.

2024-08-28 11:44 UTC, h1alexbel commented
@l3r8yJ Let's close #121, and proceed in separate ticket. This pull can be drafted.

2024-09-04 09:50 UTC, closed without merging