feat(#75): xml() simple implementation
h1alexbel/fakehub pull request #95
Opened 2024-07-23 14:50 UTC by h1alexbel

closes #75

2024-07-23 22:55 UTC, l3r8yJ requested changes
@h1alexbel take a look, please

2024-07-23 22:55 UTC, l3r8yJ commented on server/src/xml/storage.rs
> +        let mut file = File::open(self.path)?;
@h1alexbel let's deprecate it or create a puzzle to avoid `?`

```suggestion
        let mut file = File::open(self.path);
```

2024-07-23 22:55 UTC, l3r8yJ commented on server/src/xml/storage.rs
> +        assert_that!(xml.contains("<root>"), true);
@h1alexbel `assert_true` maybe?

2024-07-24 07:50 UTC, h1alexbel commented on server/src/xml/storage.rs
> +        let mut file = File::open(self.path)?;
@l3r8yJ Got it. I found the following problem statements with `?` operator:

* `?` means that the compiler can't use the question-mark to infer that the type you're collecting to is a `Result`.
* `?` calls `into`, which performs type conversion that leads to misleading result types.

Got this from this Stack Overflow  answer: https://stackoverflow.com/a/67644988/19147117

Other sources:
[What is this question mark operator about?](https://stackoverflow.com/questions/42917566/what-is-this-question-mark-operator-about)

2024-07-24 07:56 UTC, h1alexbel commented
@l3r8yJ take a look, please

2024-07-24 07:56 UTC, h1alexbel commented on server/src/xml/storage.rs
> +        let mut file = File::open(self.path)?;
@l3r8yJ should we stay with `?` in tests?

2024-07-24 09:52 UTC, l3r8yJ approved these changes
@h1alexbel looks good to me!

2024-07-24 09:54 UTC, l3r8yJ commented on server/src/xml/storage.rs
> +        let mut file = File::open(self.path)?;
@h1alexbel in tests it's fine

2024-07-24 10:17 UTC, h1alexbel commented
@rultor merge

2024-07-24 10:20 UTC, rultor commented
> @rultor merge

@h1alexbel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/42754-2247511898)

2024-07-24 10:37 UTC, merged

2024-07-24 10:38 UTC, rultor commented
> @rultor merge

@h1alexbel Done! FYI, the full log is [here](https://www.rultor.com/t/42754-2247511898) (took me 17min)